### ISSUE TITLE
NBLAST_search knitting error: cannot find allbyallblastcv4.5.desc

### ISSUE THREAD

**Issue by mmc46** [jefferislab/NBLAST_figures#2]
Knitting NBLAST_search.Rmd:
Quitting from lines 45-49 (NBLAST_search.Rmd) 
Error in fc_attach_bigmat(scoremat) : 
  Cannot find file: /Users/Carta/Library/Application Support/rpkg-flycircuit/data/bigmatrix/allbyallblastcv4.5.desc
Calls: <Anonymous> ... sort -> fc_nblast -> fc_subscoremat -> fc_attach_bigmat
Execution halted

**Comment by jefferis** [comment]
See #4. Closed by 9295ec4
