### ISSUE TITLE
Missing neuron/

### ISSUE THREAD

**Issue by mmc46** [jefferislab/NBLAST_figures#3]
It downloaded many other neurons ok for APClustering.Rmd, but got an error on this one.

Quitting from lines 52-57 (APClustering.Rmd) 
Error in download.file(url = paste0(attr(fh, "remote"), missing[i]), destfile = file.path(objDir,  : 
  cannot open URL 'http://flybrain.mrc-lmb.cam.ac.uk/si/nblast/flycircuit/data/5f83690feefa91617352393239ebdf6c'
Calls: <Anonymous> ... tryCatchOne -> <Anonymous> -> fillMissing -> download.file
Execution halted

**Comment by mmc46** [comment]
This ran ok when re-knitted, but it might be worth adding a note that if there are errors downloading data, try re-knitting.

**Comment by jefferis** [comment]
Interesting. I'm guessing that there was some kind of web timeout.

**Comment by mmc46** [comment]
Related to this, it would be worth adding a note on how much data is going to be downloaded. I got booted out of the College network for having gone over the allowed 25Gb download (in 24h).

**Comment by jefferis** [comment]
> Related to this, it would be worth adding a note on how much data is going to be downloaded. I got booted out of the College network for having gone over the allowed 25Gb download (in 24h).

Really? It should be no more than 2Gb for the similarity matrix, 1.5Gb for the neurons and then minor amounts. Suggests that something is not working with the new package versions that use "rappdirs" to download temp files to a persistent location across sessions. @ajdm any thoughts?

**Comment by jefferis** [comment]
PS Marta, would be worth updating packages including flycircuit if they are lagging behind.

**Comment by mmc46** [comment]
This was a completely new install of all packages and data, so they should be the most up to date.

**Comment by jefferis** [comment]
I think the remaining issue of excessive data transfer should now be sorted by #4. Note however that it depends on latest github versions of nat/flycircuit.
