### ISSUE TITLE
NBLAST_search.Rmd needs rewriting for end users

### ISSUE THREAD

**Issue by jefferis** [jefferislab/NBLAST_figures#4]
It currently assumes the presence of the all by all search matrix (which is really a bit big for convenient downloads) and all the neurons. I have made a new git repo that includes what seem to be the minimal set of neurons (see https://github.com/jefferislab/dpscanon).

Now it's necessary to switch this to smaller objects. @mmc46  just wanted to check whether you are working on this?

**Comment by mmc46** [comment]
No, not currently. 

Marta

**Comment by jefferis** [comment]
This is pretty much finished as of 79906bae6674513641dff40300b146210a29d85c

**Comment by jefferis** [comment]
Closed now – running fine on [travis ci](https://travis-ci.org/jefferislab/NBLAST_figures).
